import icons from "../../images/icons.svg";

import css from "./About.module.scss";
import TextSlider from "../TextSlider/TextSlider";

const About = () => {
  return (
    <section id="About">
      <div className={css.container}>
        <div className={css.about__wrapper}>
          <h2 className={css.about__title}>
            a Story that started with{" "}
            <span className={css.about__title__span}>one simple ape</span>
          </h2>

          <p className={`${css.about__text} ${css.about__upper_text}`}>
            Who got fed up with boring and hypocritic commonplace this is now
            the idea of escaping and dynamic journey on the yacht
          </p>

          <div className={css.about__lower_text}>
            <svg className={`${css.sharp__icon} ${css.sharp__icon__small}`}>
              <use href={icons + "#sharp"}></use>
            </svg>
            <p className={`${css.about__text} ${css.second}`}>
              Each artwork in the collection tells a story of one journey. Arts
              are randomly generated by users
            </p>
          </div>

          <img
            srcSet="
          /soft-ryzen/about/about-img_s@1x.png 216w, 
          /soft-ryzen/about/about-img_s@2x.png 432w, 
          /soft-ryzen/about/about-img_m@1x.png 313w, 
          /soft-ryzen/about/about-img_m@2x.png 626w, 
          /soft-ryzen/about/about-img_l@1x.png 492w, 
          /soft-ryzen/about/about-img_l@2x.png 984w"
            sizes="
                      (min-width: 1440px) 492px, 
                      (min-width: 768px) 313px, 
                      (min-width: 360px) 216px, 
                      100vw
                    "
            src="/soft-ryzen/about/about-img_s@1x.png"
            alt="Hero image"
            loading="lazy"
            className={css.about__image}
          />
        </div>
      </div>

      <TextSlider />
    </section>
  );
};

export default About;
