import icons from "/src/images/icons.svg";

import css from "./About.module.scss";

const About = () => {
  return (
    <section>
      <div className={css.container}>
        <div className={css.about__wrapper}>
          <div className={css.about__left_side}>
            <h2 className={css.about__title}>
              a Story that started with{" "}
              <span className={css.about__title__span}>one simple ape</span>
            </h2>

            <div className={css.about__lower_text}>
              <svg className={css.sharp__icon}>
                <use href={icons + "#sharp"}></use>
              </svg>
              <p className={css.about__text}>
                Each artwork in the collection tells a story of one journey.
                Arts are randomly generated by users
              </p>
            </div>
          </div>
          <div className={css.about__right_side}>
            <p className={`${css.about__text} ${css.about__upper_text}`}>
              Who got fed up with boring and hypocritic commonplace this is now
              the idea of escaping and dynamic journey on the yacht
            </p>
            <img
              src="/src/images/hero-img.png"
              alt="Hero image"
              className={css.hero__image}
            />
          </div>
        </div>

        <div className={css.animated__slider}>
          <p className={css.animated__text}>Destroy stereotypes</p>
          <svg className={css.sharp__icon}>
            <use href={icons + "#sharp"}></use>
          </svg>
          <p className={css.animated__text}>Have no limits</p>
          <svg className={css.sharp__icon}>
            <use href={icons + "#sharp"}></use>
          </svg>
          <p className={css.animated__text}>Break rules</p>
          <svg className={css.sharp__icon}>
            <use href={icons + "#sharp"}></use>
          </svg>
        </div>
      </div>
    </section>
  );
};

export default About;
