import icons from "/src/images/icons.svg";

import css from "./About.module.scss";

const About = () => {
  return (
    <section>
      <div className={css.container}>
        <h2 className={css.about__title}>
          a Story that started with{" "}
          <span className={css.about__title__span}>one simple ape</span>
        </h2>

        <p className={css.about__text}>
          Who got fed up with boring and hypocritic commonplace this is now the
          idea of escaping and dynamic journey on the yacht
        </p>
        <svg className={css.sharp__icon}>
          <use href={icons + "#sharp"}></use>
        </svg>
        <p className={css.about__text}>
          Each artwork in the collection tells a story of one journey. Arts are
          randomly generated by users
        </p>

        <div className={css.animated__slider}>
          <p className={css.animated__text}>Destroy stereotypes</p>
          <svg className={css.sharp__icon}>
            <use href={icons + "#sharp"}></use>
          </svg>
          <p className={css.animated__text}>Have no limits</p>
          <svg className={css.sharp__icon}>
            <use href={icons + "#sharp"}></use>
          </svg>
          <p className={css.animated__text}>Break rules</p>
          <svg className={css.sharp__icon}>
            <use href={icons + "#sharp"}></use>
          </svg>
        </div>
      </div>
    </section>
  );
};

export default About;
